// Generated by gencpp from file ky_033/hunt_sensor.msg
// DO NOT EDIT!


#ifndef KY_033_MESSAGE_HUNT_SENSOR_H
#define KY_033_MESSAGE_HUNT_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ky_033
{
template <class ContainerAllocator>
struct hunt_sensor_
{
  typedef hunt_sensor_<ContainerAllocator> Type;

  hunt_sensor_()
    : header()
    , sensor_id()
    , sensorValue(0.0)  {
    }
  hunt_sensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_id(_alloc)
    , sensorValue(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef float _sensorValue_type;
  _sensorValue_type sensorValue;




  typedef boost::shared_ptr< ::ky_033::hunt_sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ky_033::hunt_sensor_<ContainerAllocator> const> ConstPtr;

}; // struct hunt_sensor_

typedef ::ky_033::hunt_sensor_<std::allocator<void> > hunt_sensor;

typedef boost::shared_ptr< ::ky_033::hunt_sensor > hunt_sensorPtr;
typedef boost::shared_ptr< ::ky_033::hunt_sensor const> hunt_sensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ky_033::hunt_sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ky_033::hunt_sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ky_033

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'ky_033': ['/home/pi/catkin_ws/src/ros-ky033-node/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ky_033::hunt_sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ky_033::hunt_sensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ky_033::hunt_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ky_033::hunt_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ky_033::hunt_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ky_033::hunt_sensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ky_033::hunt_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1dd4243bbf82c08e6351700c928dda81";
  }

  static const char* value(const ::ky_033::hunt_sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1dd4243bbf82c08eULL;
  static const uint64_t static_value2 = 0x6351700c928dda81ULL;
};

template<class ContainerAllocator>
struct DataType< ::ky_033::hunt_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ky_033/hunt_sensor";
  }

  static const char* value(const ::ky_033::hunt_sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ky_033::hunt_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header           # timestamp in the header is the time the ranger\n\
                        # returned the distance reading\n\
\n\
string sensor_id        # gives sensor id \n\
\n\
float32 sensorValue     # value the sensor gives\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ky_033::hunt_sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ky_033::hunt_sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_id);
      stream.next(m.sensorValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct hunt_sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ky_033::hunt_sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ky_033::hunt_sensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor_id);
    s << indent << "sensorValue: ";
    Printer<float>::stream(s, indent + "  ", v.sensorValue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KY_033_MESSAGE_HUNT_SENSOR_H
